language: c
compiler:
- gcc
env:
  global:
  - secure: Ny8CdfjPlap0zRoL1zqsvRwC6wnUOKFFqlIcB2UTliXpPYhvpI57vj2+o9K4oMG7oGrdDE5tSMo2V3sadlQ5iQw4NSiYWBb8zErAdFoXvhHKSV3k9YUjYzc62QeZ/Ilvy8YloZlOKVe3AlNAyt4x+8+cvoJHPDGVAg6lSFWymeF7YzSJgEW4Io8nPzphE7Nuw33x3+IwO2bwbWhJx8lHkN8z5fO91p+kYkYd1/XXpJ8mBihpSdZMuU5E1cPb1UqSxo7WQLgUKkNjr9+Yi7tXTHgD+Cl+N2BOaRDwBuZOElWVmwnioLyrNdrYdPNCgsDysiqLex1lYknblzEXp7waBduK9ORXiKeoVZNNoQzQTAI/GrISGEV2VyC4N5Rar6ye1Xkl/PPRA2gQxr7mn0h+yqYgBc2u8s026MfOxIKmhewbW28EXiIBeEJGr65oeM3kkR5NyYlFl5+OqrjOt/Yp0VZTbgaZBxubum0LtD5ikW65K4iDlInvWIsGg0DKhyQdiQ7KSdIh6Qyjr5fdYRyWDgvleoF2QnsfV4pu80laF6WOfJ7DJ4mbZXlsFU84nRgHmycFDtDqdCcsn/5DJpmesEHHx5kr8/llfpYnRzoMc3Ke2NuMt5LnARG1/pqbdrEEBSeVkIuDStw0/Jyet+Vhuk0c2yQrqlJgf/jkKJNpVFA=
addons:
  coverity_scan:
    project:
      name: Oloshka/dummy_test
      description: experimental
    notification_email: nurmukhametov.alex@gmail.com
    build_command: make
    branch_pattern: master
script:
- make
