language: c
compiler:
  - gcc

env:
  global:
    - secure: "AsAweHXrwsxDLKFaU7DRWDDk5qwoOzLliMh61/8USEHyx/2HDxI9g4s+I77NrLygpBt7NKwQnH0bVVnYKnJQWvqCUBr/sWZZ6dxBSQOvkLymIkCsT3a+b42+XPXef/ZSYAjsG/GGvmOfFUpH0boL5Hp7kgYsimImmUZksbSMtxI="

addons:
  coverity_scan:
    project:
      name: "Oloshka/dummy_test"
      description: "experimental"
    notification_email: nurmukhametov.alex@gmail.com
    # build_command_prepend: ./configure
    build_command: make
    branch_pattern: master

script:
  - make

