language: c
compiler:
  - gcc

env:
  global:
    # COVERITY_SCAN_TOKEN
    # ** specific to your project **
    secure: "mdkOzyxWX0VLwxlFYh1TEMZODUPIKaGY5DBn/tUNxt+dy1VEgGKBTvC4z1twXS1aXN1LF4BzdPjB+UmTPmTLjuyP9XvHJibTb1gunQPFK39bXCoukQl6iAaHezTJUMn8XWVNnxNxzYrOd1wCNZzl2PYHloFNiCOH2AEUUWB6Zck="

script:
  - make

addons:
  coverity_scan:
    project:
      name: "Oloshka/dummy_test"
      description: "experimental"
    notification_email: nurmukhametov.alex@gmail.com
    # build_command_prepend: ./configure
    build_command: make
    branch_pattern: master
