language: c
compiler:
- gcc
env:
  global:
  - secure: YcBK+8DPOSPiCrxrRrVE/CWh4vmCLA5vRuN5snkKbQRE/VRBdAxDsLxA3EZ6KfQPrI1REiN5BD9MhwFD8EM5Aja32ajhwehUomLGsHu07Aw+IPMgEl55Rkfwsp9FH7+LrS4HA9IDKxAdhQhRfywXL7BIbKj9JHlsS7/hOdLTwWVnzeda/WhJsJuxLHl/oTMAzBJuB1h7ZQYHb7m5Wga4+JHWbTw34ciRFlpM59m8m71mj/F7QsU9cUTBmxLwtWT0t/azlOR44363QfAu4Dx2fBb+MV1XzJFVrXw98EGPJ48Sg/WU3xc1FGdE4XRom3y1+BmCUdjzL5GvW7Ubsxgp7dHuS341OiSvbDPHYDwxHDjcpbmWgFwaAzrFtnfdxr95fo2JKa5NQ4alo2HpCyrkAHwtpoQLEVfplxrvP2ESR/hArmZ2JTUjk4cd1j+aWGBJnwXu20Wa5DNjT1MIPzuL9ZVdY1RHsBtZgieQxwUO1jf0lLTr92+JYHdIO2iAaZWMbhnL6yzseJ5ysTtO9ig74dqV73x4uuwJZAazsBTP5iX7ZC9W6zAEm1v5RzPP605QR9Z0N6WaLyh3YfCilNRIV0e7iLAraJmAUiEDT7oxr2T27Nu7KG/gRdq4a5+q6nNbAb5qE2OeRzA9NAQr1wTbg4WcuRnz9E9Ij8gL0cSShVM=
addons:
  coverity_scan:
    project:
      name: Oloshka/dummy_test
      description: experimental
    notification_email: nurmukhametov.alex@gmail.com
    build_command: make
    branch_pattern: master
script:
- make
